### Create product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "MONITOR-112",
  "name": "Business Monitor",
  "price": 1199.99
}

### Create invalid product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "",
  "name": "",
  "price": -10
}

### Get all products
GET http://localhost:8080/api/products

### Get product by id
GET http://localhost:8080/api/products/153a33fd-537c-49b6-babf-af000cc968f2

### Get missing product
GET http://localhost:8080/api/products/11111111-1111-1111-1111-111111111111

### Update product
PUT http://localhost:8080/api/products/153a33fd-537c-49b6-babf-af000cc968f2
Content-Type: application/json

{
  "name": "Updated Business Laptop",
  "price": 1399.69
}

### Archive product
PATCH http://localhost:8080/api/products/153a33fd-537c-49b6-babf-af000cc968f2/archive

### Get archived products
GET http://localhost:8080/api/products/archived

### Restore archived product
PATCH http://localhost:8080/api/products/153a33fd-537c-49b6-babf-af000cc968f2/restore

### Create product with inventory
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "MONITOR-001",
  "name": "27-inch Monitor",
  "price": 399.99
}

### Get inventory by product id
GET http://localhost:8080/api/inventory/product/ae033dd4-00c2-4b57-a641-3faae8c39230

### Get missing inventory
GET http://localhost:8080/api/inventory/product/11111111-1111-1111-1111-111111111111

### Receive stock
POST http://localhost:8080/api/inventory/receive
Content-Type: application/json

{
  "productId": "ae033dd4-00c2-4b57-a641-3faae8c39230",
  "quantity": 250
}

### Get inventory transaction history
GET http://localhost:8080/api/inventory/product/1c78b0fa-75f9-4b00-ba30-9f6cbb11075a/transactions

### Missing product transaction history
GET http://localhost:8080/api/inventory/product/11111111-1111-1111-1111-111111111111/transactions

### Reserve stock
POST http://localhost:8080/api/inventory/reserve
Content-Type: application/json

{
  "productId": "8e23705e-62ce-41ee-bfdd-bda9cf823ed3",
  "quantity": 300
}

### Reserve more than available stock
POST http://localhost:8080/api/inventory/reserve
Content-Type: application/json

{
  "productId": "153a33fd-537c-49b6-babf-af000cc968f2",
  "quantity": 100000
}

### Release reserved stock
POST http://localhost:8080/api/inventory/release
Content-Type: application/json

{
  "productId": "8e23705e-62ce-41ee-bfdd-bda9cf823ed3",
  "quantity": 200
}
### Ship reserved stock
POST http://localhost:8080/api/inventory/ship
Content-Type: application/json

{
  "productId": "8e23705e-62ce-41ee-bfdd-bda9cf823ed3",
  "quantity": 2
}

### Create order with order items
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customerName": "Alexis Sanchez",
  "customerEmail": "alexis@sanchez.com",
  "address": {
    "country": "Spain",
    "city": "Madrid",
    "postalCode": "0007",
    "street": "Vamos! 07"
  },
  "items": [
    {
      "productId": "ae033dd4-00c2-4b57-a641-3faae8c39230",
      "quantity": 100
    },
    {
      "productId": "1c78b0fa-75f9-4b00-ba30-9f6cbb11075a",
      "quantity": 10
    },
    {
      "productId": "3da0f23b-0395-49dd-92bf-b39fb5904a61",
      "quantity": 22
    }
  ]
}

### Create order with insufficient reserve
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customerName": "Cristiano Ronaldo",
  "customerEmail": "CR7@SUIII.com",
  "address": {
    "country": "Spain",
    "city": "Madrid",
    "postalCode": "0007",
    "street": "Vamos! 07"
  },
  "items": [
    {
      "productId": "8e23705e-62ce-41ee-bfdd-bda9cf823ed3",
      "quantity": 10
    },
    {
      "productId": "1c78b0fa-75f9-4b00-ba30-9f6cbb11075a",
      "quantity": 799
    }
  ]
}

### Get order by ID -> INVALID
GET http://localhost:8080/api/orders/1c78b0fa-75f9-4b00-ba30-9f6cbb11075a

### Get order by ID -> VALID
GET http://localhost:8080/api/orders/6b40636f-173f-444b-a62a-eb255983f039
### Cancel order
PATCH http://localhost:8080/api/orders/75025f0d-29fc-4f1b-8bad-98b6b1e93656/cancel

### Cancel non-existing order
PATCH http://localhost:8080/api/orders/75025f0d-29fc-4f1b-8bad-98b6b1e7777/cancel

### Ship CONFIRMED order -> 200 OK
PATCH http://localhost:8080/api/orders/6b40636f-173f-444b-a62a-eb255983f039/ship

### Ship CANCELLED order -> 409 Conflict
PATCH http://localhost:8080/api/orders/75025f0d-29fc-4f1b-8bad-98b6b1e93656/ship

### Ship SHIPPED order -> 409 Conflict
PATCH http://localhost:8080/api/orders/8f85a599-9d3f-46cb-a875-1b84fc4a22d8/ship

### Ship MISSING order -> 404 Not found
PATCH http://localhost:8080/api/orders/9f99a999-9d9f-99cb-a999-9b99fc9a99d9/ship
